import {
  Activity,
  Globe,
  Zap,
  Settings2,
  Box,
  Code,
  Pipette,
  MousePointer2,
  FolderOpen,
  LayoutGrid,
  LucideIcon,
  Folder,
  Monitor,
  Network,
  ClipboardList,
  Hash,
  FileEdit,
  Lock,
  QrCode,
  Calculator,
  Clock,
  Server,
  Diff,
  Camera,
  Watch,
  Wifi,
  Gamepad2,
  Notebook,
  FileImage,
  MonitorX,
} from "lucide-react";
import { CATEGORY } from "../constants";
import { ToolPlatform } from "../lib/toolVisibility";

export interface Tool {
  id: string;
  nameKey: string;
  icon: LucideIcon;
  categoryKey: string;
  descriptionKey: string;
  color: string;
  route: string;
  requiredPermissions?: string[];
  supportedPlatforms?: ToolPlatform[];
}

export const TOOLS: Tool[] = [
  {
    id: "notepad",
    nameKey: "tools.notepad.name",
    icon: Notebook,
    categoryKey: "categories.system",
    descriptionKey: "tools.notepad.description",
    color: "#f43f5e",
    route: "/tools/notepad",
  },
  {
    id: "folder_size",
    nameKey: "tools.folder_size.name",
    icon: FolderOpen,
    categoryKey: "categories.files",
    descriptionKey: "tools.folder_size.description",
    color: "#409eff",
    route: "/tools/folder-size",
  },
  {
    id: "hash_calculator",
    nameKey: "tools.hash_calculator.name",
    icon: Hash,
    categoryKey: "categories.files",
    descriptionKey: "tools.hash_calculator.description",
    color: "#8b5cf6",
    route: "/tools/hash-calculator",
  },
  {
    id: "batch_renamer",
    nameKey: "tools.batch_renamer.name",
    icon: FileEdit,
    categoryKey: "categories.files",
    descriptionKey: "tools.batch_renamer.description",
    color: "#ec4899",
    route: "/tools/batch-renamer",
  },
  {
    id: "ocr",
    nameKey: "tools.ocr.name",
    icon: Camera,
    categoryKey: "categories.system",
    descriptionKey: "tools.ocr.description",
    color: "#10b981",
    route: "/tools/ocr",
  },
  {
    id: "clicker",
    nameKey: "tools.clicker.name",
    icon: MousePointer2,
    categoryKey: "categories.system",
    descriptionKey: "tools.clicker.description",
    color: "#10b981",
    route: "/tools/clicker",
  },
  {
    id: "node_cleaner",
    nameKey: "tools.node_cleaner.name",
    icon: Box,
    categoryKey: "categories.dev",
    descriptionKey: "tools.node_cleaner.description",
    color: "#67c23a",
    route: "/tools/node-cleaner",
  },
  {
    id: "variable_naming",
    nameKey: "tools.variable_naming.name",
    icon: Code,
    categoryKey: "categories.dev",
    descriptionKey: "tools.variable_naming.description",
    color: "#6366f1",
    route: "/tools/variable-naming",
  },
  {
    id: "unit_converter",
    nameKey: "tools.unit_converter.name",
    icon: Calculator,
    categoryKey: "categories.dev",
    descriptionKey: "tools.unit_converter.description",
    color: "#10b981",
    route: "/tools/unit-converter",
  },
  {
    id: "cron_generator",
    nameKey: "tools.cron_generator.name",
    icon: Clock,
    categoryKey: "categories.dev",
    descriptionKey: "tools.cron_generator.description",
    color: "#06b6d4",
    route: "/tools/cron-generator",
  },
  {
    id: "json_format",
    nameKey: "tools.json_format.name",
    icon: Code,
    categoryKey: "categories.dev",
    descriptionKey: "tools.json_format.description",
    color: "#409eff",
    route: "/tools/json-format",
  },
  {
    id: "base64_encoder",
    nameKey: "tools.base64_encoder.name",
    icon: Lock,
    categoryKey: "categories.dev",
    descriptionKey: "tools.base64_encoder.description",
    color: "#f59e0b",
    route: "/tools/base64-encoder",
  },
  {
    id: "translator",
    nameKey: "tools.translator.name",
    icon: Globe,
    categoryKey: "categories.dev",
    descriptionKey: "tools.translator.description",
    color: "#14b8a6",
    route: "/tools/translator",
  },
  {
    id: "color_picker",
    nameKey: "tools.color_picker.name",
    icon: Pipette,
    categoryKey: "categories.dev",
    descriptionKey: "tools.color_picker.description",
    color: "#e91e63",
    route: "/tools/color-picker",
  },
  {
    id: "qrcode_tool",
    nameKey: "tools.qrcode_tool.name",
    icon: QrCode,
    categoryKey: "categories.dev",
    descriptionKey: "tools.qrcode_tool.description",
    color: "#9c27b0",
    route: "/tools/qrcode",
  },
  {
    id: "image_converter",
    nameKey: "tools.image_converter.name",
    icon: Camera,
    categoryKey: "categories.files",
    descriptionKey: "tools.image_converter.description",
    color: "#ff7043",
    route: "/tools/image-converter",
  },
  {
    id: "pdf_to_image",
    nameKey: "pdf_to_image.name",
    icon: FileImage,
    categoryKey: "categories.files",
    descriptionKey: "pdf_to_image.description",
    color: "#e53935",
    route: "/tools/pdf-to-image",
  },
  {
    id: "clipboard_manager",
    nameKey: "tools.clipboard_manager.name",
    icon: ClipboardList,
    categoryKey: "categories.system",
    descriptionKey: "tools.clipboard_manager.description",
    color: "#10b981",
    route: "/tools/clipboard-manager",
  },
  {
    id: "my_computer_namespace",
    nameKey: "tools.my_computer_namespace.name",
    icon: MonitorX,
    categoryKey: "categories.system",
    descriptionKey: "tools.my_computer_namespace.description",
    color: "#ef4444",
    route: "/tools/my-computer-namespace",
    supportedPlatforms: ["windows"],
  },
  {
    id: "dns_tool",
    nameKey: "tools.dns_tool.name",
    icon: Globe,
    categoryKey: "categories.network",
    descriptionKey: "tools.dns_tool.description",
    color: "#3f51b5",
    route: "/tools/dns-tool",
  },
  {
    id: "nginx_editor",
    nameKey: "tools.nginx_editor.name",
    icon: Server,
    categoryKey: "categories.network",
    descriptionKey: "tools.nginx_editor.description",
    color: "#009639",
    route: "/tools/nginx-editor",
  },
  {
    id: "diff_tool",
    nameKey: "tools.diff_tool.name",
    icon: Diff,
    categoryKey: "categories.dev",
    descriptionKey: "tools.diff_tool.description",
    color: "#6366f1",
    route: "/tools/diff-tool",
  },
  {
    id: "timestamp_converter",
    nameKey: "tools.timestamp_converter.name",
    icon: Watch,
    categoryKey: "categories.dev",
    descriptionKey: "tools.timestamp_converter.description",
    color: "#ec4899",
    route: "/tools/timestamp-converter",
  },
  {
    id: "ip_lookup",
    nameKey: "tools.ip_lookup.name",
    icon: Wifi,
    categoryKey: "categories.network",
    descriptionKey: "tools.ip_lookup.description",
    color: "#3f51b5",
    route: "/tools/ip-lookup",
  },
  {
    id: "simple_web_server",
    nameKey: "tools.simple_web_server.name",
    icon: Server,
    categoryKey: "categories.network",
    descriptionKey: "tools.simple_web_server.description",
    color: "#06b6d4",
    route: "/tools/simple-web-server",
  },
  {
    id: "port_scanner",
    nameKey: "tools.port_scanner.name",
    icon: Activity,
    categoryKey: "categories.network",
    descriptionKey: "tools.port_scanner.description",
    color: "#f43f5e",
    route: "/tools/port-scanner",
  },
  {
    id: "game2048",
    nameKey: "tools.game2048.name",
    icon: LayoutGrid,
    categoryKey: "categories.entertainment",
    descriptionKey: "tools.game2048.description",
    color: "#edc22e",
    route: "/tools/2048",
  },
  {
    id: "othello",
    nameKey: "tools.othello.title",
    icon: Gamepad2,
    categoryKey: "categories.entertainment",
    descriptionKey: "tools.othello.description",
    color: "#1b5e20",
    route: "/othello",
  },
  {
    id: "settings",
    nameKey: "tools.settings.name",
    icon: Settings2,
    categoryKey: "categories.system",
    descriptionKey: "tools.settings.description",
    color: "#64748b",
    route: "/settings",
  },
];
export const CATEGORIES = [
  { name: CATEGORY.ALL, key: "categories.all", icon: LayoutGrid },
  { name: "文件工具", key: "categories.files", icon: Folder },
  { name: "系统工具", key: "categories.system", icon: Monitor },
  { name: "网络工具", key: "categories.network", icon: Network },
  { name: "开发工具", key: "categories.dev", icon: Code },
  { name: "娱乐工具", key: "categories.entertainment", icon: Zap },
];
